whitelist_rules:
  - comma
  - class_delegate_protocol
  - line_length
  - file_length
  - function_body_length
  - trailing_newline
  - trailing_comma
  - trailing_whitespace
  - vertical_whitespace
  - void_return
  - colon
  - control_statement
  - discarded_notification_center_observer
  - empty_enum_arguments
  - empty_parentheses_with_trailing_closure
  - force_try
  - force_cast
  - leading_whitespace
  - legacy_cggeometry_functions
  - legacy_constant
  - legacy_constructor
  - weak_delegate
  - vertical_parameter_alignment
excluded: 
  - Carthage
  - Pods
  - Sources/Addons
  - Shared/Addons
  - .vendor
line_length:
  warning: 220
  error: 300
  ignores_comments: true
  ignores_function_declarations: true
file_length:
  warning: 700
  error: 1200
function_body_length:
  warning: 300
  error: 440
